// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZcWeAVN3rPmPETnXvtpT9S6QGzaNLJQ',
    appId: '1:1058439936847:web:73fa464d6994b62000a33a',
    messagingSenderId: '1058439936847',
    projectId: 'phan-phoi-son-gia-si',
    authDomain: 'phan-phoi-son-gia-si.firebaseapp.com',
    storageBucket: 'phan-phoi-son-gia-si.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq6AJ_AsrzPfGzrydIwlFRcp2cV4f1324',
    appId: '1:1058439936847:android:441f37dcf27cfd0b00a33a',
    messagingSenderId: '1058439936847',
    projectId: 'phan-phoi-son-gia-si',
    storageBucket: 'phan-phoi-son-gia-si.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDXBVJZGoHbJPY-pjS1FWcBjciatDPOLg',
    appId: '1:1058439936847:ios:b091eb954e65ffd600a33a',
    messagingSenderId: '1058439936847',
    projectId: 'phan-phoi-son-gia-si',
    storageBucket: 'phan-phoi-son-gia-si.firebasestorage.app',
    iosBundleId: 'com.example.phanPhoiSonGiaSi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDXBVJZGoHbJPY-pjS1FWcBjciatDPOLg',
    appId: '1:1058439936847:ios:b091eb954e65ffd600a33a',
    messagingSenderId: '1058439936847',
    projectId: 'phan-phoi-son-gia-si',
    storageBucket: 'phan-phoi-son-gia-si.firebasestorage.app',
    iosBundleId: 'com.example.phanPhoiSonGiaSi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQZcWeAVN3rPmPETnXvtpT9S6QGzaNLJQ',
    appId: '1:1058439936847:web:cc670dca80a2970100a33a',
    messagingSenderId: '1058439936847',
    projectId: 'phan-phoi-son-gia-si',
    authDomain: 'phan-phoi-son-gia-si.firebaseapp.com',
    storageBucket: 'phan-phoi-son-gia-si.firebasestorage.app',
  );
}
